package dns

import (
	"strings"

	"golang.org/x/net/publicsuffix"
)

func isParkedDomainNs(domain string) bool {
	domain = strings.TrimSuffix(domain, ".")
	baseDomain := extractBaseDomain(domain)

	return parkedDomansNS[baseDomain] || parkedDomansNS[domain]
}

func extractBaseDomain(domain string) string {
	baseDomain, err := publicsuffix.EffectiveTLDPlusOne(domain)
	if err != nil {
		return domain
	}

	return baseDomain
}

// TODO: Move this to the database
var parkedDomansNS = map[string]bool{
	"above.com":                   true,
	"afternic.com":                true,
	"alter.com":                   true,
	"bodis.com":                   true,
	"bookmyname.com":              true,
	"brainydns.com":               true,
	"brandbucket.com":             true,
	"chookdns.com":                true,
	"cnomy.com":                   true,
	"commonmx.com":                true,
	"dan.com":                     true,
	"day.biz":                     true,
	"dingodns.com":                true,
	"directnic.com":               true,
	"dne.com":                     true,
	"dnslink.com":                 true,
	"dnsnuts.com":                 true,
	"dnsowl.com":                  true,
	"dnsspark.com":                true,
	"domain-for-sale.at":          true,
	"domain-for-sale.se":          true,
	"domaincntrol.com":            true,
	"domainhasexpired.com":        true,
	"domainist.com":               true,
	"domainmarket.com":            true,
	"domainmx.com":                true,
	"domainorderdns.nl":           true,
	"domainparking.ru":            true,
	"domainprofi.de":              true,
	"domainrecover.com":           true,
	"dsredirection.com":           true,
	"dsredirects.com":             true,
	"eftydns.com":                 true,
	"emailverification.info":      true,
	"emu-dns.com":                 true,
	"expiereddnsmanager.com":      true,
	"expirationwarning.net":       true,
	"expired.uniregistry-dns.com": true,
	"fabulous.com":                true,
	"failed-whois-verification.namecheap.com": true,
	"fastpark.net":            true,
	"freenom.com":             true,
	"gname.net":               true,
	"hastydns.com":            true,
	"hostresolver.com":        true,
	"ibspark.com":             true,
	"kirklanddc.com":          true,
	"koaladns.com":            true,
	"magpiedns.com":           true,
	"malkm.com":               true,
	"markmonitor.com":         true,
	"mijndomein.nl":           true,
	"milesmx.com":             true,
	"mytrafficmanagement.com": true,
	"name.com":                true,
	"namedynamics.net":        true,
	"nameprovider.net":        true,
	"ndsplitter.com":          true,
	"ns01.cashparking.com":    true,
	"ns02.cashparking.com":    true,
	"ns1.domain-is-4-sale-at-domainmarket.com": true,
	"ns1.domain.io":                        true,
	"ns1.namefind.com":                     true,
	"ns1.park.do":                          true,
	"ns1.pql.net":                          true,
	"ns1.smartname.com":                    true,
	"ns1.sonexo.eu":                        true,
	"ns1.undeveloped.com":                  true,
	"ns2.domain.io":                        true,
	"ns2.domainmarket.com":                 true,
	"ns2.namefind.com":                     true,
	"ns2.park.do":                          true,
	"ns2.pql.net":                          true,
	"ns2.smartname.com":                    true,
	"ns2.sonexo.com":                       true,
	"ns2.undeveloped.com":                  true,
	"ns3.tppns.com":                        true,
	"ns4.tppns.com":                        true,
	"nsresolution.com":                     true,
	"one.com":                              true,
	"onlydomains.com":                      true,
	"panamans.com":                         true,
	"park1.encirca.net":                    true,
	"park2.encirca.net":                    true,
	"parkdns1.internetvikings.com":         true,
	"parkdns2.internetvikings.com":         true,
	"parking-page.net":                     true,
	"parking.namecheap.com":                true,
	"parking1.ovh.net":                     true,
	"parking2.ovh.net":                     true,
	"parkingcrew.net":                      true,
	"parkingpage.namecheap.com":            true,
	"parkingspa.com":                       true,
	"parklogic.com":                        true,
	"parktons.com":                         true,
	"perfectdomain.com":                    true,
	"quokkadns.com":                        true,
	"redirectdom.com":                      true,
	"redmonddc.com":                        true,
	"registrar-servers.com":                true,
	"renewyourname.net":                    true,
	"rentondc.com":                         true,
	"rookdns.com":                          true,
	"rzone.de":                             true,
	"sav.com":                              true,
	"searchfusion.com":                     true,
	"searchreinvented.com":                 true,
	"securetrafficrouting.com":             true,
	"sedo.com":                             true,
	"sedoparking.com":                      true,
	"smtmdns.com":                          true,
	"snparking.ru":                         true,
	"squadhelp.com":                        true,
	"sslparking.com":                       true,
	"tacomadc.com":                         true,
	"taipandns.com":                        true,
	"thednscloud.com":                      true,
	"torresdns.com":                        true,
	"trafficcontrolrouter.com":             true,
	"trustednam.es":                        true,
	"uniregistrymarket.link":               true,
	"verify-contact-details.namecheap.com": true,
	"voodoo.com":                           true,
	"weaponizedcow.com":                    true,
	"wombatdns.com":                        true,
	"wordpress.com":                        true,
	"www.undeveloped.com----type.in":       true,
	"your-browser.this-domain.eu":          true,
	"ztomy.com":                            true,
}
